### ISSUE TITLE
Please make a release of this new version to support grails 2.5.x

### ISSUE THREAD

**Issue by antondelpiero** [grails-plugins/grails-cache-redis#6]
Hi Graeme,
 We have test the new plugin for grails 2.5.x and it works just fine. The problem is that, it still haven't released yet. Can you please release this version so we can use it directly from maven?

Thx

**Comment by davidklebanoff** [comment]
Yes, a new release would be much appreciated.

**Comment by gtors** [comment]
@donbeave @graemerocher - Could you please bump a release version?

**Comment by talpalaru** [comment]
We too really really need a released version. Is there any reason why this does not happen?

**Comment by graemerocher** [comment]
Grails 2.5.x is in maintenance mode as are all the plugins. You are welcome to go through our support channels if you want a release https://grails.org/support.html
